### ISSUE TITLE
environmental contour problem

### ISSUE THREAD

**Issue by Wadbled** [WEC-Sim/WDRT#5]
Hello,

I am new at using the WDRT toolbox on Python and tried to use it for a site specific set of data.
The set is concerning a range of buoys of the SWAN model, each recording date, hour and characteristic of the hourly wave spectrum. The data available are Hs, the mean direction, peak direction and energy distribution. Are available as well Mean wave period, energy period, peak period and zero-upcrossing period. 
I want to analyse the data from some of these buoys in order to get the 50 and 100 year return contour.

First I wrote files for 1 buoy, year by year, gathering the spectral components of each hourly sea state, guessing the spectrum was a Pierson Moskowitz.
The I ran the envSampling scripts for these files and obtain the contour enclosed. 

My questions are : 
What is likely to cause these obviously wrong results ? 
Is it possible to deal directly with the significant height and energy or peak period as input ? It would save me from errors while remaking the spectras.

Many thanks for any help
Xavier
![contour_example](https://cloud.githubusercontent.com/assets/28778051/26195842/0042a692-3bb5-11e7-99bc-c91b9fd3c130.png)

**Comment by rgcoe** [comment]
@Wadbled - Sorry for the slow reply on this. There is certainly is something going wrong with the case you're showing here. Based on your description, this does sound like something the code should be able to handle. Some questions to get this resolve:

1. You say you're assuming a PM spectrum to create the files that replicate the NDBC .txt files from your SWAN data. However, you also state that you have the raw spectral distribution. Why then would you need to assume an idealized spectrum?
2. I haven't seen anything like the odd behavior you're seeing here before. Could you share the .txt files you're using so that I could help with the debugging?

- Ryan

**Comment by Wadbled** [comment]
@ryancoe- Thank you for the reply Ryan! 

1) I assume an idealized spectrum because from what I understand from your code, it deals straightforward with input data as a spectral distribution. I agree that I could have used the spectral characterisation I have but it seemed easier to modify them so I could just get the code running on similar data as NDBC. 

Attached you will find the txt files I have been using as well as the initial data I have available.  the PLOCAN_P25_waves.txt is the initial file I have been provided and the zip folder has the data I converted.

Thanks again
Xavier

[PLOCAN_P25_waves.txt](https://github.com/WEC-Sim/WDRT/files/1057742/PLOCAN_P25_waves.txt)

[NBDC1.zip](https://github.com/WEC-Sim/WDRT/files/1057753/NBDC1.zip)

**Comment by rgcoe** [comment]
@Wadbled  - Thanks. We've received your files and are looking into the issue now.

**Comment by aubreyeckert** [comment]
@Wadbled We have reviewed the data that you sent. The density of the data presents tri-modal behavior (see plot below) that is not easily characterized by the methods for estimating the Hs-T joint probability distribution.  The contour preforms better when the bin size is set to a larger value (green line), meaning that the joint probability distribution does not follow the data characteristics as closely.

![contour_density](https://user-images.githubusercontent.com/13546010/26955649-5e9495ae-4c75-11e7-8583-256b178f1cec.jpg)

I believe that the method might perform better if we were able to use the original data (raw spectral distribution) or the Hs-T data that you calculated. If you could send us the data, we can run the code with it and see if we can get better results. 

Thanks,
Aubrey

**Comment by Wadbled** [comment]
@aubreyeckert 
Thank you for reviewing my data. I suppose that when you say tri-modal behavior you are referring to the irregular shape of the density distribution ? 

Unfortunately I have been provided the txt file as a raw data from a buoy, so I don't know if the raw spectral data is available... I have attached the data in terms of Hs-Tp and other spectral characteristics for 3 other buoys.

Xavier
[PLOCAN_raw.zip](https://github.com/WEC-Sim/WDRT/files/1063463/PLOCAN_raw.zip)

**Comment by aubreyeckert** [comment]
@Wadbled Yes, the tri-modal behavior I was referring to is the shape of the density distribution. I checked out the data for three buoys you sent and it does not appear to have this behavior:
![plocan_p16 density](https://user-images.githubusercontent.com/13546010/27100819-9599fc04-503c-11e7-8b22-15cb1b9444e4.png)
I used the significant wave height and energy period values to calculate contours with the ESSC code for each of these buoys. The results look much better: 
![plocan16_contour](https://user-images.githubusercontent.com/13546010/27100894-de9d0bb2-503c-11e7-93ef-24040db587c5.png)
An example of the code that I used to create this contour is shown below. The buoy object can be created by setting Hs and T directly as shown after reading the data from the text files in to Python:
```python
# Import packages
import matplotlib.pyplot as plt
import WDRT.ESSC as ESSC

# Read in data from text files as you want

# Create buoy object
buoy16 = ESSC.Buoy('16')

# Set Hs and T directly from data (each must be 1D array)
buoy16.Hs = Hs_Plocan16
buoy16.T = T_Plocan16

# Create PCA EA object
pca16 = ESSC.PCA(buoy16)

# Declare required parameters
Time_SS = 1.  # Sea state duration (hrs)
Time_R = 100  # Return periods (yrs) of interest

# Calculate contour
pca_Hs_Return, pca_T_Return = pca16.getContours(Time_SS, Time_R)

plt.figure()
plt.plot(buoy16.T, buoy16.Hs, 'bo', alpha=0.1, label='PLOCAN16 data')
plt.plot(pca_T_Return, pca_Hs_Return, 'k-', label='100 year contour')
plt.legend(loc='lower right', fontsize='small')
plt.grid(True)
plt.xlabel('Energy period, $T_e$ [s]')
plt.ylabel('Sig. wave height, $H_s$ [m]')
plt.savefig('PLOCAN16_Contour.png',dpi=300)
plt.show()
```
If you are able to get the Hs and T values for any buoy, you can follow this workflow to calculate the contours. Let me know if this works for you or if you run into any additional issues.

Thanks,
Aubrey

**Comment by Wadbled** [comment]
@aubreyeckert Thank you very much, I managed to get similar contours for all the buoys available. 
I still got a few questions though:
Do you have an idea why the code is having trouble while analysing the peak period ? To my understanding  it is a statistical analysis that should work independently of the data type. I tried the code you propose with directly peak and energy period and the results with the peak periods kept showing trimodal behavior while the energy period gave more sensible results.

I tried as well the analysis for 20 and 30 years return period (which are the approximate period covered by the buoys) and was surprised not to get a contour close to the data points. 

Thanks,
Xavier

**Comment by aubreyeckert** [comment]
@Wadbled I spoke to one of our researchers here who works with these sea state variables often. She indicated that the peak period is sensitive to peaks in the spectrum while the energy period is more robust. She also mentioned that, depending on the frequency resolution, peak period can have a larger discretization at larger values. These two things could help explain why the density of the peak period is behaving so oddly, and why the contours behave better for the energy period. 

The method should work independently of the data type for the most part, but there are some parametric assumptions built in regarding the shapes of conditional distributions and the construction of the joint distribution shared by the two variables. The inherent data density will impact these fits and thus the contours.

As far as the 20 and 30 year contours and their relationship to the data, this is a continuing area of research on the method. If you are interested, we have also included some additional contour methods in the latest version of the WDRT toolbox that use copulas to generate the contours. These might fit the data more closely at lower return periods, but have been found to have their own drawbacks. 

Please let me know if I can provide any additional information.

Thanks,
Aubrey

**Comment by huyquangtranaus** [comment]
Hi everyone, I am new to this toolbox, so please help with a question:

Is there any function/routine in WDRT that can read the full wave spectra to get Hs and wave energy period?

Thank you in advance,

Best Regards,
Huy

**Comment by DinaPerei** [comment]
Hello everyone

I've tried to run your script example for PLOCAN16, but I get the error in the line buoy16 = ESSC.Buoy('16'):
TypeError: __init__() missing 1 required positional argument: 'buoyType'.
I need to do something like this, the 100 and 50 return periods, but using the Hs/Tp from the netcdf files of cds.climate.copernicus.eu.
I'm new to this toolbox and python, so I'm sorry if this is a basic question.
The followed script was the one I used:

 #Import packages
import matplotlib.pyplot as plt
import WDRT.ESSC as ESSC

# Read in data from text files as you want

Hs_Plocan16=[]
T_Plocan16=[]

with open('PLOCAN_P16_waves.txt') as f:
    for i in range(19):
        next(f)
    for line in f:
        splitLine=line.split(",")
        Hs_Plocan16.append(splitLine[1])
        T_Plocan16.append(splitLine[7])
f.close()

# Create buoy object
buoy16 = ESSC.Buoy('16')

# Set Hs and T directly from data (each must be 1D array)
buoy16.Hs = Hs_Plocan16
buoy16.T = T_Plocan16

# Create PCA EA object
pca16 = ESSC.PCA(buoy16)

# Declare required parameters
Time_SS = 1.  # Sea state duration (hrs)
Time_R = 100  # Return periods (yrs) of interest

# Calculate contour
pca_Hs_Return, pca_T_Return = pca16.getContours(Time_SS, Time_R)

plt.figure()
plt.plot(buoy16.T, buoy16.Hs, 'bo', alpha=0.1, label='PLOCAN16 data')
plt.plot(pca_T_Return, pca_Hs_Return, 'k-', label='100 year contour')
plt.legend(loc='lower right', fontsize='small')
plt.grid(True)
plt.xlabel('Energy period, $T_e$ [s]')
plt.ylabel('Sig. wave height, $H_s$ [m]')
plt.savefig('PLOCAN16_Contour.png',dpi=300)
plt.show()

Thank you
